import Head from "next/head";

export default function SinglePostPage() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-full justify-center">
        <div> Post View</div>
      </main>
    </>
  );
}
